# Generated by Django 3.0.7 on 2020-06-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='项目名称', max_length=200, unique=True, verbose_name='项目名称')),
                ('leader', models.CharField(help_text='项目负责人', max_length=50, verbose_name='项目负责人')),
                ('tester', models.CharField(help_text='测试人员', max_length=50, verbose_name='测试人员')),
                ('programmer', models.CharField(help_text='开发人员', max_length=50, verbose_name='开发人员')),
                ('desc', models.TextField(blank=True, default='xxx简介', help_text='项目简介', null=True, verbose_name='项目简介')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
        ),
    ]
